"use client";

import { motion } from "framer-motion";
import { Beaker, Layers, Sparkles, Zap } from "lucide-react";

const experiments = [
  {
    title: "AI-Powered Diff Engine",
    category: "LLM Utility",
    description: "A specialized tool for visualizing code changes generated by AI models with semantic understanding.",
    icon: <Zap className="w-5 h-5" />,
    status: "Experimental",
  },
  {
    title: "Glassy UI Framework",
    category: "UI/UX",
    description: "A lightweight CSS-in-JS library focused entirely on high-performance glassmorphism and micro-interactions.",
    icon: <Layers className="w-5 h-5" />,
    status: "Beta",
  },
  {
    title: "Smart Garden IoT",
    category: "Hardware",
    description: "An automated irrigation system using ESP32 and React Native with real-time moisture monitoring.",
    icon: <Sparkles className="w-5 h-5" />,
    status: "Completed",
  },
];

export const TheLab = () => {
  return (
    <section id="the-lab" className="py-24 px-6 bg-[#0A0A0A] border-t border-white/5">
      <div className="max-w-7xl mx-auto">
        <div className="space-y-4 mb-16 text-center">
          <div className="inline-flex items-center gap-2 text-blue-500 font-bold text-xs uppercase tracking-[0.2em]">
            <Beaker className="w-4 h-4" /> The Experiment Lab
          </div>
          <h2 className="text-3xl md:text-5xl font-bold">Where Ideas Take Shape</h2>
          <p className="text-gray-500 max-w-2xl mx-auto text-sm md:text-base font-light">
            A collection of prototypes, research projects, and technical experiments that push the boundaries of my daily stack.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {experiments.map((exp, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="group p-8 bg-white/[0.02] border border-white/5 rounded-[2.5rem] hover:bg-white/[0.04] transition-all relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-6 opacity-5 group-hover:opacity-10 transition-opacity">
                <Beaker className="w-24 h-24" />
              </div>
              
              <div className="p-3 w-fit rounded-2xl bg-blue-500/10 text-blue-500 mb-6 group-hover:scale-110 transition-transform">
                {exp.icon}
              </div>

              <div className="space-y-3 relative z-10">
                <div className="flex justify-between items-center">
                  <span className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">{exp.category}</span>
                  <span className="text-[9px] text-blue-500 font-bold uppercase tracking-widest px-2 py-0.5 rounded-full bg-blue-500/10 border border-blue-500/20">{exp.status}</span>
                </div>
                <h4 className="text-xl font-bold text-white">{exp.title}</h4>
                <p className="text-gray-400 text-xs leading-relaxed font-light">{exp.description}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};
